buildscript {
    repositories {
        google()
        mavenCentral()
        maven { url = uri("https://oss.sonatype.org/content/repositories/snapshots/") }
        maven { url = uri("https://oss.sonatype.org/content/repositories/releases/") }
    }
    dependencies {
        classpath "com.android.tools.build:gradle:9.2.1"
    }
}

ext {
    appName = "Epic Ball Adventure"
    gdxVersion = "1.14.0"
    gwtVersion = "2.11.0"
}

allprojects {
    version = "1.0.0"

    repositories {
        google()
        mavenCentral()
        maven { url = uri("https://oss.sonatype.org/content/repositories/snapshots/") }
        maven { url = uri("https://oss.sonatype.org/content/repositories/releases/") }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.layout.buildDirectory
}
